# Generated by Django 3.2.12 on 2022-03-30 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Irrigator',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=180)),
                ('water_flow', models.FloatField()),
                ('status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Specie',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=180)),
                ('water_consumption', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('species', models.CharField(max_length=180)),
                ('salary', models.FloatField()),
                ('planting_date', models.DateField()),
                ('irrigator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.irrigator')),
                ('specie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.specie')),
            ],
        ),
    ]
