# Generated by Django 3.2.12 on 2022-03-31 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plant',
            name='salary',
        ),
        migrations.RemoveField(
            model_name='plant',
            name='species',
        ),
    ]
